Update Dockerfile

diff --git a/docker/images/n8n/Dockerfile b/docker/images/n8n/Dockerfile
--- a/docker/images/n8n/Dockerfile
+++ b/docker/images/n8n/Dockerfile
@@ -1,2 +1,27 @@
-FROM n8nio/n8n
-USER NODE
+ARG NODE_VERSION=16
+FROM n8nio/base:${NODE_VERSION}
+
+ARG N8N_VERSION=0.231.3
+RUN if [ -z "$N8N_VERSION" ] ; then echo "The N8N_VERSION argument is missing!" ; exit 1; fi
+
+ENV N8N_VERSION=${N8N_VERSION}
+ENV NODE_ENV=production
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+	'armv7') apk --no-cache add --virtual build-dependencies python3 build-base;; \
+	esac && \
+	npm install -g --omit=dev n8n@${N8N_VERSION} && \
+	case "$apkArch" in \
+	'armv7') apk del build-dependencies;; \
+	esac && \
+	find /usr/local/lib/node_modules/n8n -type f -name "*.ts" -o -name "*.js.map" -o -name "*.vue" | xargs rm && \
+	rm -rf /root/.npm \
+  chown -R node /home/node
+
+# Set a custom user to not have n8n run as root
+
+USER node
+WORKDIR /data
+COPY docker-entrypoint.sh /docker-entrypoint.sh
+ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
